### ISSUE TITLE
Maze is not a dodecahedron

### ISSUE THREAD

**Issue by BartMassey** [pistacchio/wumpus-rust#2]
The rules of Hunt the Wumpus specify that the maze is a dodecahedron. The current maze generator produces a maze that is, as far as I can work out, 5 tetrahedrons connected in a line. This is quite different from the original game and from the Rosetta Code game rules, and provides a quite different gameplay feel.

If it is not desired to fix this, it would be nice to at least correct the help text to no longer describe the maze as a dodecahedron.

**Comment by BartMassey** [comment]
Actually, I was wrong. The maze currently consists of 5 disconnected tetrahedrons. This makes it unwinnable most of the time, since the wumpus is usually unreachable. (You might get lucky with bats.)

PR incoming.

**Comment by BartMassey** [comment]
Fixed in PR #3. Includes a test for maze connectivity.

**Comment by pistacchio** [comment]
You are right. I wrote a small Python script to actually graph the generated maze and indeed it generates five disconnected "circles". I merged your PR that solves the problem and overall simplifies the maze generation
